name: Home
version: 1.0
main: dein.package.HomePlugin
api-version: 1.20 # Oder deine Version
commands:
  sethome:
    description: Setzt dein Zuhause
  home:
    description: Teleportiert dich nach Hause
